#spring.application.name=demo

#server.port=8080
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
spring.datasource.url=jdbc:postgresql://ep-autumn-union-a2yofcss.eu-central-1.aws.neon.tech/neondb?sslmode=require

# 2. Utilizatorul bazei tale de date (este textul dinaintea celor două puncte)
spring.datasource.username=neondb_owner

# 3. Parola bazei de date
# (În imagine apare cu steluțe. Dă click pe ochiul mic din Neon pe care scrie "Show password" ca să o vezi, apoi copiază o și lipește o aici)
spring.datasource.password=npg_4BvPjALgdU5w

# 4. Driverul și setările de Hibernate (Asigură-te că le ai adăugate)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.mail.host=smtp.resend.com
spring.mail.port=465
spring.mail.username=resend
spring.mail.password=${RESEND_API_KEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory


# Ajustare HikariCP pentru Neon Serverless
spring.datasource.hikari.max-lifetime=45000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.validation-timeout=2000
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=5

# Trimite un ping periodic ca conexiunea să nu fie închisă de Neon
spring.datasource.hikari.keepalive-time=20000
spring.datasource.hikari.connection-test-query=SELECT 1