#spring.application.name=demo
#profitshare.data.path=src/main/resources/products.json
#
#server.port=8080
spring.datasource.url=jdbc:postgresql://ep-autumn-union-a2yofcss.eu-central-1.aws.neon.tech/neondb?sslmode=require

# 2. Utilizatorul bazei tale de date (este textul dinaintea celor două puncte)
spring.datasource.username=neondb_owner

# 3. Parola bazei de date
# (În imagine apare cu steluțe. Dă click pe ochiul mic din Neon pe care scrie "Show password" ca să o vezi, apoi copiază o și lipește o aici)
spring.datasource.password=npg_rHB0N7WTUYOD

# 4. Driverul și setările de Hibernate (Asigură-te că le ai adăugate)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#profitshare.data.path=./data/profitshare
profitshare.data.path=products.json